version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0.2
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn -B verify jacoco:report sonar:sonar -Pcoverage
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco

workflows:
  maven_test:
    jobs:
      - build:
          context: SonarCloud