name: Docker image build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress --color=always package
      - name: Upload jars
        uses: actions/upload-artifact@v7
        with:
          name: jars
          path: target/**/*.jar
  amd64-image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v6
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: jars
          path: target/
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          build-args: OBTAIN_COMPILED_JAR_FROM=docker_host
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/gavvvr/oracle-sql-rearranger:amd64_latest

  arm64-image:
    needs: build
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v6
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: jars
          path: target/
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          build-args: OBTAIN_COMPILED_JAR_FROM=docker_host
          platforms: linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/gavvvr/oracle-sql-rearranger:arm64_latest
