name: Maven CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: temurin
      - name: Build with Maven
        run: mvn --batch-mode package
      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path:
            target/oracle-sql-rearranger.jar
            target/lib/
  arm64-image:
    needs: build
    runs-on: ubuntu-22.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jars
      - name: test
        run: tree
#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/arm64
#          push: true
#          tags: ghcr.io/gavvvr/oracle-sql-rearranger:test2

  amd64-image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jars
      - name: test
        run: tree
#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: ghcr.io/gavvvr/oracle-sql-rearranger:test2
